kumuluzee:
  name: reservations-service
  env:
    name: dev
    address: 10.245.44.197
  address: 10.245.44.197
  version: 1.0.0
  server:
    base-url: http://10.245.44.197
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ReservationsDS
      connection-url: ${PG_HOST}
      username: ${PG_USER}
      password: ${PG_PASSWORD}
      pool:
        max-size: 1
  cors-filter:
    servlet:
      allow-origin: "*"
  discovery:
    cluster: rso-cluster
    consul:
      agent: http://10.244.1.32:8500
  #logs:
  #  config-file: '<?xml version="1.0" encoding="UTF-8"?>
  #                        <Configuration name="comments">
  #                            <Appenders>
  #                                <Console name="console" target="SYSTEM_OUT">
  #                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
  #                                </Console>
  #                                <Socket name="logstash" host="f69f79f0-67ac-4674-9c9d-7cccc6aa6062-ls.logit.io"
  #                                port="26288" protocol="udp">
  #                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
  #                                </Socket>
  #                            </Appenders>
  #                            <Loggers>
  #                                <!-- Default logger -->
  #                                <Root level="all">
  #                                    <AppenderRef ref="console" level="info" />
  #                                    <AppenderRef ref="logstash" level="trace" />
  #                                </Root>
  #                            </Loggers>
  #                        </Configuration>'
  config:
    consul:
      agent: ${CONSUL_HOST}
  health:
    checks:
      data-source-health-check:
        type: readiness
        jndi-name: jdbc/ReservationsDS

